/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TicTacToeGame;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author Meteor
 */
public class TicTacToeGame extends javax.swing.JFrame {

    /**
     * Creates new form TicTacToeGame
     */
    public TicTacToeGame() {
        initComponents();
        setTitle("Tic Tac Toe Game");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(true);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(new BorderLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        Player1VSPlayer2 = new com.k33ptoo.components.KButton();
        HumanVSComputer = new com.k33ptoo.components.KButton();
        exit = new com.k33ptoo.components.KButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 229, 202));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(186, 205, 219)));
        kGradientPanel1.setkEndColor(new java.awt.Color(137, 55, 95));
        kGradientPanel1.setkStartColor(new java.awt.Color(252, 200, 209));

        jLabel1.setFont(new java.awt.Font("Romande ADF Style Std", 1, 24)); // NOI18N
        jLabel1.setText("Tic Tac Toe Game");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(204, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, -1, -1));

        Player1VSPlayer2.setText("Player1 VS Player2");
        Player1VSPlayer2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Player1VSPlayer2.setkBorderRadius(20);
        Player1VSPlayer2.setkEndColor(new java.awt.Color(237, 198, 177));
        Player1VSPlayer2.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        Player1VSPlayer2.setkHoverStartColor(new Color(73,13,198,120));
        Player1VSPlayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Player1VSPlayer2ActionPerformed(evt);
            }
        });
        jPanel1.add(Player1VSPlayer2, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 114, 187, -1));

        HumanVSComputer.setText("Human VS Computer");
        HumanVSComputer.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        HumanVSComputer.setkBorderRadius(20);
        HumanVSComputer.setkEndColor(new java.awt.Color(237, 198, 177));
        HumanVSComputer.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        HumanVSComputer.setkHoverStartColor(new Color(73,13,198,120));
        HumanVSComputer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HumanVSComputerActionPerformed(evt);
            }
        });
        jPanel1.add(HumanVSComputer, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 194, 187, -1));

        exit.setText("EXIT");
        exit.setFont(new java.awt.Font("Romande ADF Std", 1, 14)); // NOI18N
        exit.setkBorderRadius(20);
        exit.setkEndColor(new java.awt.Color(237, 198, 177));
        exit.setkHoverForeGround(new java.awt.Color(51, 51, 51));
        exit.setkHoverStartColor(new Color(73,13,198,120));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 274, 187, -1));

        kGradientPanel2.setkEndColor(new java.awt.Color(137, 55, 95));
        kGradientPanel2.setkStartColor(new java.awt.Color(252, 200, 209));
        kGradientPanel2.setPreferredSize(new java.awt.Dimension(320, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TicTacToeGame/TicTacToeGamePic.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel1.add(kGradientPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JFrame frame;
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(frame,"Confrim if you want to exit", "Tic Tac Toe Game", JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitActionPerformed

    private void HumanVSComputerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HumanVSComputerActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HumanVsComputer().setVisible(true);
    }//GEN-LAST:event_HumanVSComputerActionPerformed

    private void Player1VSPlayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Player1VSPlayer2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new HumanVsHuman().setVisible(true);
    }//GEN-LAST:event_Player1VSPlayer2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToeGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToeGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton HumanVSComputer;
    private com.k33ptoo.components.KButton Player1VSPlayer2;
    private com.k33ptoo.components.KButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    // End of variables declaration//GEN-END:variables
}
